### PR TITLE
SaaS simple example with Carina and jclouds

### PR DESCRIPTION
**Pull request by zack-shoylev**

### CODE REVIEW

**Comment by everett-toews** [comment]
The repo is https://github.com/getcarina/examples. The full path to this example would be https://github.com/getcarina/examples/carina_saas_example/ which is looking pretty redundant. I'd rather see something about Java and/or jclouds in the directory name so people know what they're dealing with at a glance.

**Comment by zack-shoylev** [comment]
This wasn't quite ready to be merged yet. What happened? @rgbkrk

**Comment by rgbkrk** [comment]
I didn't see a WIP tag or "do not merge". Would you like to revert?

**Comment by zack-shoylev** [comment]
I think ill make changes in a new PR. @everett-toews wanted a rename, and I'm running some extra tests.

**Pull request merged**
